name: social_media_feed_project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  path_provider: ^2.0.11
dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  very_good_analysis: ^3.1.0
  mockito: ^5.0.0
flutter:


  uses-material-design: true

  